interface=wlan0
driver=nl80211
ssid=HwHiAiUser_WiFi_5G
# a 代表 5GHz 频段
hw_mode=a
# 149 是国内 5G 非常稳定且合规的信道
channel=149

# --- 以下是解开速度封印的关键参数 ---
# 开启 QoS，高速网络必需
wmm_enabled=1
# 开启 802.11n (WiFi 4) 支持
ieee80211n=1
# 开启 802.11ac (WiFi 5) 支持
ieee80211ac=1

ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=12345678
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
country_code=CN
